[project]
name = "example"
r_version = "4.4"

repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
    "tibble",
    { name = "dplyr", git = "https://github.com/tidyverse/dplyr", branch = "main" },
]

