name: Deploy Preview to Netlify

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request:
permissions:
  statuses: write
  contents: write
  issues: write
  deployments: write
  pull-requests: write

jobs:
  deploy:
    #needs: build
    runs-on: ubuntu-latest
    environment:
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: nelonoel/branch-name@v1.0.1
      - run: bun install 
      - name: build
        run: bun run build
      # since the site is currently on github pages on /rv-docs we need
      # to shift the dir structure around on netlify to also represent that subpath
      - name: setup
        run: |
          mkdir build
          mv dist build
          mv build/dist build/rv-docs
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta http-equiv="refresh" content="0; url=./rv-docs/">
              <title>Redirecting...</title>
          </head>
          <body>
              <p>Redirecting to documentation...</p>
              <p>If you are not redirected automatically, <a href="./rv-docs/">click here</a>.</p>
          </body>
          </html>
          EOF
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1      

