name: Check Links in Docs

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    name: Link Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: './dist/**/*.html --verbose --exclude ^mailto:'
          output: lychee/output.txt
          format: text
          fail: false  # Allow post-processing instead

      - name: Check for "Cannot find file" failures
        run: |
          echo 'Scanning lychee output...'
          if grep -q 'Failed: Cannot find file' lychee/output.txt; then
            echo '❌ Broken local file links detected'
            exit 1
          else
            echo '✅ No file-not-found errors'
          fi